"""update_projects

Revision ID: 7691e6efa2d4
Revises: cb2dfc0d7049
Create Date: 2026-01-13 17:37:10.668654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7691e6efa2d4'
down_revision: Union[str, Sequence[str], None] = 'cb2dfc0d7049'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requirements',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('depth', sa.String(length=255), nullable=False),
    sa.Column('description_text', sa.String(length=1023), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('projects', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('projects', 'status',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('projects', 'created_by_user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_unique_constraint(None, 'projects', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='unique')
    op.alter_column('projects', 'created_by_user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('projects', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('projects', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_table('requirements')
    # ### end Alembic commands ###
